### ISSUE TITLE
Add docs for 'u-hide-until' and 'u-show-until' CSS classes.

### ISSUE THREAD

**Issue by michaelsavchuk** [Pixelrobin/limbs#1]
Add a section to the [`index.html`](https://github.com/Pixelrobin/limbs/blob/master/index.html) docs documenting the 'u-show-until' and 'u-hide-until' classes in [`limbs.css`](https://github.com/Pixelrobin/limbs/blob/master/css/limbs.css#L534). The ideal location would be after or in the utilities section in [`index.html`](https://github.com/Pixelrobin/limbs/blob/master/index.html#L542). Look at other examples to see how they're made. Additional CSS you need to add to the index should be added in [`landing-page.css`](https://github.com/Pixelrobin/limbs/blob/master/extra/landing-page.css)

The challenge: Make sure that after your changes the page is ideal for printing on a standard page size (ctrl/command+p), as each of the sections use the `avoid-page-break` class, which makes the printer try to fit them all on a page without breaking. This can result in long blank sections if you're not careful.

**Comment by Pixelrobin** [comment]
Update: these classes will be removed in the first release, so the docs are no longer needed. I'll reopen if they're reimplemented later.

**Comment by michaelsavchuk** [comment]
Update: these classes will be removed in the first release, so the docs are no longer needed. I'll reopen if they're reimplemented later.
