### ISSUE TITLE
Fix index.html formatting

### ISSUE THREAD

**Issue by michaelsavchuk** [Pixelrobin/limbs#2]
Fix some bad formatting in [`index.html`](https://github.com/Pixelrobin/limbs/blob/master/index.html) due to bad habits.

1. Convert indentation to spaces with a width of 2 characters
2. Remove spacing from attribute assignments in html elements, for instance, convert `<div class = "u-full-width"></div>` into `<div class="u-full-width"></div>`.
3. Replace all the comments that look like
    
    ```
    <!-- Comment
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    ```
    into `<!-- Comment -->`.

I'm willing to split the issue into multiple PRs from different people.

**Comment by katiequin335** [comment]
I can work on this

**Comment by michaelsavchuk** [comment]
Update, @katiequin335 updated the spacing and comments, all that is left to do is to convert the indentation to 2 character width spaces :)

Edit: Wait, it looks like git likes to ignore changes to indent styles...? Anyone know how to bypass this?

**Comment by karltanjuan** [comment]
I can do it :)

**Comment by michaelsavchuk** [comment]
@karltanjuan @katiequin335 thanks guys! :D

**Comment by karltanjuan** [comment]
you're welcome @Pixelrobin :D
